[package]
name = "openrr-plugin"
version = "0.0.6"
authors = ["Taiki Endo <taiki@smilerobotics.com>"]
edition = "2018"
license = "Apache-2.0"
description = "Experimental plugin support for arci"
keywords = ["robotics", "robot"]
categories = ["science::robotics"]
repository = "https://github.com/openrr/openrr"
documentation = "https://docs.rs/openrr-plugin"

[dependencies]
abi_stable = "0.9.3"
anyhow = "1"
arci = "0.0.6"
num-traits = "0.2"
tokio = { version = "1", features = ["sync", "rt-multi-thread"] }

[dev-dependencies]
assert_approx_eq = "1"
criterion = "0.3"
fs-err = "2"
tokio = { version = "1", features = ["full"] }

[[bench]]
name = "proxy"
harness = false
