version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: ''
    ignore:
      # These dependencies need to be updated at the same time with urdf-viz.
      - dependency-name: urdf-rs
      - dependency-name: k
      - dependency-name: nalgebra
      - dependency-name: ncollide3d
      # These dependencies need to be updated at the same time with tonic.
      - dependency-name: prost
      - dependency-name: prost-types
      - dependency-name: tonic-build
      # These dependencies need to be updated at the same time with eframe.
      - dependency-name: egui_extras
    labels: []
