version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: ''
    ignore:
      # These dependencies need to be updated at the same time.
      - dependency-name: k
      - dependency-name: nalgebra
      - dependency-name: ncollide3d
      - dependency-name: urdf-viz
    labels: []
