version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: ''
    ignore:
      # These dependencies need to be updated at the same time with urdf-viz.
      - dependency-name: k
      - dependency-name: nalgebra
      - dependency-name: ncollide3d
      # These dependencies need to be updated at the same time with tonic.
      - dependency-name: prost
      - dependency-name: prost-types
    labels: []
