# https://rust-lang.github.io/rust-clippy/master/#disallowed_types
disallowed-types = [
    # use faster `parking_lot::{Mutex, RwLock, CondVar}` instead
    "std::sync::Mutex",
    "std::sync::RwLock",
    "std::sync::CondVar",
    # TODO: use `reason =` syntax once 1.57 became stable:
    # { path = "std::sync::Mutex", reason = "use faster `parking_lot::Mutex` instead" },
]
