# https://embarkstudios.github.io/cargo-deny/checks/advisories/cfg.html
[advisories]
yanked = "deny"
ignore = [
    "RUSTSEC-2020-0027", # traitobject 0.1, transitively dep of rosrust (via xml-rpc)
    "RUSTSEC-2020-0071", # time 0.1, transitively dep of rosrust (via xml-rpc)
    "RUSTSEC-2021-0078", # hyper 0.10, transitively dep of rosrust (via xml-rpc)
    "RUSTSEC-2021-0079", # hyper 0.10, transitively dep of rosrust (via xml-rpc)
    "RUSTSEC-2022-0006", # thread_local 0.3, transitively dep of rosrust (via xml-rpc)
    "RUSTSEC-2022-0013", # regex 0.2, transitively dep of rosrust (via xml-rpc)
    "RUSTSEC-2022-0022", # hyper 0.10, transitively dep of rosrust (via xml-rpc)
    "RUSTSEC-2021-0144", # unmaintained (traitobject), transitively dep of rosrust (via xml-rpc)
    "RUSTSEC-2021-0146", # unmaintained (twoway), transitively dep of rosrust (via xml-rpc)
    "RUSTSEC-2021-0150", # unmaintained (ncollide3d)
    "RUSTSEC-2023-0028", # unmaintained (buf_redux), transitively dep of rosrust (via xml-rpc)
    "RUSTSEC-2023-0050", # unmaintained (multipart), transitively dep of rosrust (via xml-rpc)
    "RUSTSEC-2023-0081", # unmaintained (safemem), transitively dep of rosrust (via xml-rpc)
    "RUSTSEC-2024-0014", # unmaintained (generational-arena), dep of abi_stable
    "RUSTSEC-2024-0320", # unmaintained (yaml-rust), dep of rosrust
]

# https://embarkstudios.github.io/cargo-deny/checks/bans/cfg.html
[bans]
multiple-versions = "allow" # TODO
wildcards = "allow" # https://github.com/EmbarkStudios/cargo-deny/issues/448
skip = []

# https://embarkstudios.github.io/cargo-deny/checks/licenses/cfg.html
[licenses]
unused-allowed-license = "deny"
private.ignore = true
allow = [
    "Apache-2.0",
    "MIT",
    "Unicode-3.0", # unicode-ident
    "BSD-2-Clause",
    "BSD-3-Clause",
    "BSL-1.0",
    "ISC",
    "OpenSSL",
    "Zlib",
    "MPL-2.0", # webpki-roots
    "OFL-1.1", # epaint
    "LicenseRef-UFL-1.0", # epaint (see https://github.com/emilk/egui/issues/2321)
    "Unicode-3.0",
]

[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 }
]

# https://embarkstudios.github.io/cargo-deny/checks/sources/cfg.html
[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-git = []
