[workspace]

# arci-ros is excluded to make it independent from ROS

members = [
    "arci",
    "arci-gamepad-gilrs",
    "arci-urdf-viz",
    "openrr",
    "openrr-client",
    "openrr-planner",
    "openrr-sleep",
    "openrr-teleop",
]

[patch.crates-io]

"arci" = {path = "arci"}
"arci-gamepad-gilrs" = {path = "arci-gamepad-gilrs"}
# "arci-ros" = {path = "arci-ros"}
"arci-urdf-viz" = {path = "arci-urdf-viz"}
"openrr" = {path = "openrr"}
"openrr-client" = {path = "openrr-client"}
"openrr-planner" = {path = "openrr-planner"}
"openrr-sleep" = {path = "openrr-sleep"}
"openrr-teleop" = {path = "openrr-teleop"}
