[workspace]

members = [
    "arci",
    "arci-gamepad-gilrs",
    "arci-ros",
    "arci-speak-cmd",
    "arci-urdf-viz",
    "openrr",
    "openrr-apps",
    "openrr-client",
    "openrr-command",
    "openrr-gui",
    "openrr-planner",
    "openrr-sleep",
    "openrr-teleop",
]

[patch.crates-io]

"arci-speak-cmd" = {path = "arci-speak-cmd"}
"arci" = {path = "arci"}
"arci-gamepad-gilrs" = {path = "arci-gamepad-gilrs"}
"arci-ros" = {path = "arci-ros"}
"arci-urdf-viz" = {path = "arci-urdf-viz"}
"openrr" = {path = "openrr"}
"openrr-apps" = {path = "openrr-apps"}
"openrr-client" = {path = "openrr-client"}
"openrr-command" = {path = "openrr-command"}
"openrr-gui" = {path = "openrr-gui"}
"openrr-planner" = {path = "openrr-planner"}
"openrr-sleep" = {path = "openrr-sleep"}
"openrr-teleop" = {path = "openrr-teleop"}
# TODO remove
k = { git = 'https://github.com/openrr/k', branch = 'support_serde_default' }
