[package]
name = "arci-gamepad-gilrs"
version = "0.0.1"
authors = ["Takashi Ogura <ogura@smilerobotics.com>"]
edition = "2018"
license = "Apache-2.0"
description = "arci::Gamepad implementation using gilrs"
keywords = ["robotics", "robot"]
categories = ["science::robotics"]
repository = "https://github.com/openrr/openrr"

[dependencies]
arci = "0.0.1"
crossbeam-channel = "0.5.0"
gilrs = { version = "0.8", features = ["serde-serialize"] }
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_with = "1.5"

[dev-dependencies]
tokio = { version = "1.0", features = ["full"] }
