[package]
name = "openrr"
version = "0.0.1"
authors = ["Takashi Ogura <ogura@smilerobotics.com>"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/OpenRR/openrr"
homepage = "https://openrr.github.io"


[features]
default = ["assimp"]
assimp = ["openrr-planner/assimp"]

[dependencies]
openrr-client = { path = "../openrr-client", version = "0.0.1" }
openrr-sleep = { path = "../openrr-sleep", version = "0.0.1" }
openrr-planner = { path = "../openrr-planner", version = "0.0.1" }
openrr-teleop = { path = "../openrr-teleop", version = "0.0.1" }
