[package]
name = "openrr"
version = "0.0.1"
authors = ["Takashi Ogura <ogura@smilerobotics.com>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://openrr.github.io"
description = "Open Rust Robotics framework"
keywords = ["robotics", "robot"]
categories = ["science::robotics"]
repository = "https://github.com/openrr/openrr"
readme = "../README.md"

[features]
default = ["assimp"]
assimp = ["openrr-planner/assimp"]
ros = ["openrr-apps/ros"]

[dependencies]
openrr-apps = "0.0.1"
openrr-client = "0.0.1"
openrr-command = "0.0.1"
openrr-planner = "0.0.1"
openrr-sleep = "0.0.1"
openrr-teleop = "0.0.1"
