[package]
name = "openrr-apps"
version = "0.0.4"
authors = ["Mitsuharu Kojima <kojima@smilerobotics.com>"]
edition = "2018"
license = "Apache-2.0"
description = "applications using openrr"
keywords = ["robotics", "robot"]
categories = ["science::robotics"]
repository = "https://github.com/openrr/openrr"
documentation = "http://docs.rs/openrr-apps"
readme = "README.md"

[features]
default = ["gui", "ros"]
ros = ["arci-ros"]
gui = ["openrr-gui"]

[dependencies]
anyhow = "1.0"
arci = "0.0.4"
arci-gamepad-gilrs = "0.0.4"
arci-speak-audio = "0.0.4"
arci-speak-cmd = "0.0.4"
arci-urdf-viz = "0.0.4"
async-recursion = "0.3"
async-trait = "0.1"
k = "0.23"
openrr-client = "0.0.4"
openrr-command = "0.0.4"
openrr-teleop = "0.0.4"
rand = "0.8.0"
serde = { version = "1.0", features = ["derive"] }
structopt = "0.3.21"
thiserror = "1.0"
tokio = { version = "1.0", features = ["full"] }
toml = "0.5"
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = "0.2"
urdf-rs = "0.6"

arci-ros = { version = "0.0.4", optional = true }
openrr-gui = { version = "0.0.4", optional = true }

[dev-dependencies]

[[bin]]
name = "openrr_apps_robot_command"
path = "src/bin/robot_command.rs"

[[bin]]
name = "openrr_apps_robot_teleop"
path = "src/bin/robot_teleop.rs"

[[bin]]
name = "openrr_apps_joint_position_sender"
path = "src/bin/joint_position_sender.rs"
required-features = ["gui"]
