[package]
name = "openrr-apps"
version = "0.0.1"
authors = ["Mitsuharu Kojima <kojima@smilerobotics.com>"]
edition = "2018"
license = "Apache-2.0"

[features]
ros = ["arci-ros", "rand"]

[dependencies]
arci = { version = "0.0.1", path = "../arci" }
arci-gamepad-gilrs = { version = "0.0.1", path = "../arci-gamepad-gilrs" }
arci-urdf-viz = { version = "0.0.1", path = "../arci-urdf-viz" }
async-recursion = "0.3"
async-trait = "0.1"
env_logger = "0.8"
k = "0.22"
log = "0.4"
openrr-client = { version = "0.0.1", path = "../openrr-client" }
openrr-command = { version = "0.0.1", path = "../openrr-command" }
openrr-teleop = { version = "0.0.1", path = "../openrr-teleop" }
serde = { version = "1.0", features = ["derive"] }
structopt = "0.3.21"
thiserror = "1.0"
tokio = { version = "1.0", features = ["full"] }
toml = "0.5"
urdf-rs = "0.6"

arci-ros = {version="0.0.1", optional = true}
rand = {version="0.8.0", optional = true}

[dev-dependencies]

[[bin]]
name = "openrr_apps_robot_command"
path = "src/bin/robot_command.rs"

[[bin]]
name = "openrr_apps_robot_teleop"
path = "src/bin/robot_teleop.rs"
