[package]
name = "openrr-teleop"
version = "0.0.3"
authors = ["Takashi Ogura <ogura@smilerobotics.com>"]
edition = "2018"
license = "Apache-2.0"
description = "openrr teleoperation library"
keywords = ["robotics", "robot"]
categories = ["algorithms", "science::robotics"]
repository = "https://github.com/openrr/openrr"

[dependencies]
arci = "0.0.3"
async-trait = "0.1"
auto_impl = "0.4.1"
k = "0.22"
openrr-client = "0.0.3"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1"
