[package]
name = "arci-speak-cmd"
version = "0.0.3"
authors = ["Taiki Endo <te316e89@gmail.com>"]
edition = "2018"
license = "Apache-2.0"
description = "arci::Speaker implementation using local command"
keywords = ["robotics", "robot"]
categories = ["science::robotics"]
repository = "https://github.com/openrr/openrr"
documentation = "http://docs.rs/arci-speak-cmd"

[dependencies]
arci = "0.0.3"
async-trait = "0.1"
thiserror = "1.0"

[dev-dependencies]
structopt = "0.3"
tokio = { version = "1", features = ["full"] }
tracing-subscriber = "0.2"
