[package]
name = "arci-speak-cmd"
version = "0.1.0"
authors = ["Taiki Endo <te316e89@gmail.com>"]
edition = "2018"
license = "Apache-2.0"
description = "arci::Speaker implementation using local command"
keywords = ["robotics", "robot"]
categories = ["science::robotics"]
repository = "https://github.com/openrr/openrr"

[dependencies]
arci = "0.0.3"
log = "0.4"
thiserror = "1.0"

[dev-dependencies]
env_logger = "0.8"
structopt = "0.3"
