[package]
name = "openrr-client"
version = "0.0.1"
authors = ["Takashi Ogura <ogura@smilerobotics.com>"]
edition = "2018"
license = "Apache-2.0"
description = "openrr useful client libraries"
keywords = ["robotics", "robot"]
categories = ["science::robotics"]
repository = "https://github.com/openrr/openrr"

[dependencies]
anyhow = "1.0"
arci = "0.0.1"
async-trait = "0.1"
k = { version = "0.22", features = ["serde-serialize"] }
log = "0.4"
openrr-planner = "0.0.1"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
urdf-rs = "0.6"

[dev-dependencies]
assert_approx_eq = "1.1"
