[package]
name = "openrr-client"
version = "0.0.3"
authors = ["Takashi Ogura <ogura@smilerobotics.com>"]
edition = "2018"
license = "Apache-2.0"
description = "openrr useful client libraries"
keywords = ["robotics", "robot"]
categories = ["science::robotics"]
repository = "https://github.com/openrr/openrr"
documentation = "http://docs.rs/openrr-client"

[dependencies]
anyhow = "1.0"
arci = "0.0.3"
async-trait = "0.1"
k = { version = "0.23", features = ["serde-serialize"] }
openrr-planner = "0.0.3"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
tracing = { version = "0.1", features = ["log"] }
urdf-rs = "0.6"

[dev-dependencies]
assert_approx_eq = "1.1"
