[package]
name = "openrr-client"
version = "0.0.1"
authors = ["Takashi Ogura <ogura@smilerobotics.com>"]
edition = "2018"

[dependencies]
arci = { version="0.0.1", path = "../arci"}
async-trait = "0.1"
k = "0.21"
thiserror = "1.0"
openrr-planner = { version = "0.0.1", path = "../openrr-planner" }
anyhow = "1.0"
log = "0.4"

[dev-dependencies]
