[package]
name = "openrr-internal-codegen"
version = "0.0.0"
edition.workspace = true
publish = false

[dependencies]
anyhow = "1"
fs-err = "2"
heck = "0.4"
prettyplease = "=0.1.23"
proc-macro2 = "1"
quote = "1"
syn = { version = "1", features = ["full", "visit-mut"] }
tempfile = "3"
