[package]
name = "openrr-remote"
version = "0.0.6"
authors = ["Taiki Endo <taiki@smilerobotics.com>"]
edition = "2021"
license = "Apache-2.0"
description = "Remote execution support for arci"
keywords = ["robotics", "robot"]
categories = ["science::robotics"]
repository = "https://github.com/openrr/openrr"

[build-dependencies]
tonic-build = "0.6"

[dependencies]
arci = "0.0.6"
prost = "0.9"
prost-types = "0.9"
tokio = { version = "1", features = ["rt-multi-thread"] }
tonic = "0.6"
tracing = "0.1"

[dev-dependencies]
anyhow = "1"
assert_approx_eq = "1"
tokio = { version = "1", features = ["full"] }
