[package]
name = "arci-ros"
version = "0.0.1"
authors = ["Takashi Ogura <t.ogura@gmail.com>"]
edition = "2018"

[dependencies]
rosrust = "0.9"
nalgebra = "0.23"
thiserror = "1.0"
ros-nalgebra = "0.0.3"
arci = {path = "../arci"}
anyhow = "1.0"
paste = "1.0"
async-trait = "0.1"
crossbeam-channel = "0.5.0"
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1", features = ["derive"] }

[dev-dependencies]

k = "0.21"

# for tests/utils (using same version of rosrust 0.9.5)

[target.'cfg(unix)'.dev-dependencies]
nix = "0.15.0"
