[package]
name = "arci-ros"
version = "0.0.1"
authors = ["Takashi Ogura <t.ogura@gmail.com>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
anyhow = "1.0"
arci = { path = "../arci" }
async-trait = "0.1"
crossbeam-channel = "0.5.0"
nalgebra = "0.24"
paste = "1.0"
ros-nalgebra = "0.0.4"
rosrust = "0.9"
serde = { version = "1", features = ["derive"] }
thiserror = "1.0"
tokio = { version = "1.0", features = ["full"] }

[dev-dependencies]
k = "0.22"

# for tests/utils (using same version of rosrust 0.9.5)

[target.'cfg(unix)'.dev-dependencies]
nix = "0.15.0"
