[package]
name = "arci-ros"
version = "0.0.5"
authors = ["Takashi Ogura <t.ogura@gmail.com>"]
edition = "2018"
license = "Apache-2.0"
description = "arci implementation using ROS1"
keywords = ["robotics", "robot"]
categories = ["science::robotics"]
repository = "https://github.com/openrr/openrr"
documentation = "https://docs.rs/arci-ros"

[dependencies]
anyhow = "1.0"
arci = "0.0.5"
flume = "0.10"
nalgebra = "0.26"
once_cell = "1"
paste = "1.0"
ros-nalgebra = "0.0.5"
rosrust = "0.9"
schemars = "0.8.3"
serde = { version = "1", features = ["derive"] }
thiserror = "1.0"
tokio = { version = "1.0", features = ["full"] }
urdf-rs = "0.6"

[dev-dependencies]
k = "0.24"

# for tests/utils (using same version of rosrust 0.9.5)

[target.'cfg(unix)'.dev-dependencies]
nix = "0.21.0"
