[package]
name = "arci-speak-audio"
version = "0.0.3"
authors = ["shinjo"]
edition = "2018"
license = "Apache-2.0"
description = "arci::Speaker implementation for playing audio files"
keywords = ["robotics", "robot"]
categories = ["science::robotics"]
repository = "https://github.com/openrr/openrr"

[dependencies]
arci = "0.0.3"
rodio = "0.13.0"
thiserror = "1.0"
tracing = "0.1"

[dev-dependencies]
structopt = "0.3"
tracing-subscriber = "0.2"
