[package]
name = "arci-speak-audio"
version = "0.0.4"
authors = ["Koki Shinjo <sktometometo@gmail.com>"]
edition = "2018"
license = "Apache-2.0"
description = "arci::Speaker implementation for playing audio files"
keywords = ["robotics", "robot"]
categories = ["science::robotics"]
repository = "https://github.com/openrr/openrr"
documentation = "http://docs.rs/arci-speak-audio"

[dependencies]
arci = "0.0.4"
rodio = "0.13.0"
thiserror = "1.0"
tracing = { version = "0.1", features = ["log"] }

[dev-dependencies]
structopt = "0.3"
tracing-subscriber = "0.2"
