[package]
name = "arci-speak-audio"
version = "0.0.3"
authors = ["shinjo"]
edition = "2018"
license = "Apache-2.0"
description = "arci::Speaker implementation for playing audio files"
keywords = ["robotics", "robot"]
categories = ["science::robotics"]
repository = "https://github.com/openrr/openrr"
documentation = "http://docs.rs/arci-speak-audio"

[dependencies]
arci = "0.0.3"
async-trait = "0.1"
rodio = "0.13.0"
thiserror = "1.0"

[dev-dependencies]
structopt = "0.3"
tokio = { version = "1", features = ["full"] }
tracing-subscriber = "0.2"
