[package]
name = "arci-urdf-viz"
version = "0.0.3"
authors = ["Takashi Ogura <ogura@smilerobotics.com>"]
edition = "2018"
license = "Apache-2.0"
description = "arci implementation using urdf-viz"
keywords = ["robotics", "robot"]
categories = ["science::robotics"]
repository = "https://github.com/openrr/openrr"

[dependencies]
anyhow = "1.0"
arci = "0.0.3"
async-trait = "0.1"
log = "0.4"
nalgebra = "0.24"
openrr-planner = { version = "0.0.3", default-features = false }
openrr-sleep = "0.0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ureq = { version = "2", features = ["json"] }
url = "2.0"

[dev-dependencies]
assert_approx_eq = "1.1"
rouille = "3.0"
serde_derive = "1.0"
tokio = { version = "1.0", features = ["full"] }
tokio-test = "0.4"
