[package]
name = "arci-urdf-viz"
version = "0.0.1"
authors = ["Takashi Ogura <ogura@smilerobotics.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
arci = { version = "0.0.1", path = "../arci" }
async-trait = "0.1"
log = "0.4"
nalgebra = "0.23"
openrr-planner = { version = "0.0.1", default-features = false }
openrr-sleep = { version = "0.0.1", path = "../openrr-sleep" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ureq = { version = "2", features = ["json"] }
url = "2.0"

[dev-dependencies]
assert_approx_eq = "1.1"
rouille = "2.1.0"
serde_derive = "1.0"
tokio = { version = "1.0", features = ["full"] }
tokio-test = "0.4"
