[package]
name = "arci-urdf-viz"
version = "0.0.1"
authors = ["Takashi Ogura <ogura@smilerobotics.com>"]
edition = "2018"

[dependencies]
arci = { version = "0.0.1", path = "../arci" }
reqwest = { version = "0.10", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
openrr-planner = {version = "0.0.1", default-features=false}
nalgebra = "0.23"
async-trait = "0.1"
openrr-sleep = { version = "0.0.1", path = "../openrr-sleep"}

[dev-dependencies]
assert_approx_eq = "1.1"
rouille = "2.1.0"
serde_derive = "1.0"
tokio = { version = "0.2", features = ["full"] }
tokio-test = "*"
