[package]
name = "openrr-command"
version = "0.0.5"
authors = ["Mitsuharu Kojima <kojima@smilerobotics.com>"]
edition = "2018"
license = "Apache-2.0"
description = "openrr command line tool library"
keywords = ["robotics", "robot"]
categories = ["science::robotics"]
repository = "https://github.com/openrr/openrr"
documentation = "https://docs.rs/openrr-command"

[dependencies]
arci = "0.0.5"
async-recursion = "0.3"
k = "0.24"
openrr-client = "0.0.5"
structopt = "0.3.21"
thiserror = "1.0"
tracing = { version = "0.1", features = ["log"] }
