[package]
name = "openrr-command"
version = "0.0.1"
authors = ["Mitsuharu Kojima <kojima@smilerobotics.com>"]
edition = "2018"
license = "Apache-2.0"
description = "openrr command line tool library"
keywords = ["robotics", "robot"]
categories = ["science::robotics"]
repository = "https://github.com/openrr/openrr"

[dependencies]
arci = "0.0.1"
async-recursion = "0.3"
k = "0.22"
log = "0.4"
openrr-client = "0.0.1"
structopt = "0.3.21"
thiserror = "1.0"
