robot_config_path = "pr2_robot_client_config_for_urdf_viz.toml"

[control_nodes_config]
move_base_mode = "base"

[control_nodes_config.joints_pose_sender_config]

[[control_nodes_config.ik_node_teleop_configs]]
solver_name = "r_arm_with_torso_ik_solver"
joint_trajectory_client_name = "r_arm_with_torso_collision_checked"

[control_nodes_config.ik_node_teleop_configs.config]
mode = "right arm i k"

[[control_nodes_config.ik_node_teleop_configs]]
solver_name = "l_arm_with_torso_ik_solver"
joint_trajectory_client_name = "l_arm_with_torso_collision_checked"

[control_nodes_config.ik_node_teleop_configs.config]
mode = "left arm i k"

[[control_nodes_config.joy_joint_teleop_configs]]
client_name = "r_arm_with_torso_collision_checked"

[control_nodes_config.joy_joint_teleop_configs.config]
mode = "right arm"

[[control_nodes_config.joy_joint_teleop_configs]]
client_name = "l_arm_with_torso_collision_checked"

[control_nodes_config.joy_joint_teleop_configs.config]
mode = "left arm"

[[control_nodes_config.joy_joint_teleop_configs]]
client_name = "torso"

[control_nodes_config.joy_joint_teleop_configs.config]
mode = "torso"
joint_step = 0.05
