urdf_viz_clients_configs = []
use_move_base_urdf_viz_web_client = false
use_navigation_urdf_viz_web_client = false
urdf_viz_clients_total_complete_allowable_error = 0.02
urdf_viz_clients_complete_timeout_sec = 10.0
ros_cmd_vel_move_base_client_config.topic = "/base_controller/command"

[[ros_clients_configs]]
name = "l_arm"
joint_names = ["l_shoulder_pan_joint", "l_shoulder_lift_joint", "l_upper_arm_roll_joint", "l_elbow_flex_joint", "l_forearm_roll_joint", "l_wrist_flex_joint", "l_wrist_roll_joint"]
wrap_with_joint_velocity_limiter = false
joint_velocity_limits = []
complete_allowable_errors = [10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0]
complete_timeout_sec = 10.0
controller_name = "l_arm_controller"
state_topic_name = "l_arm_controller/openrr/state"
send_partial_joints_goal = false

[[ros_clients_configs]]
name = "r_arm"
joint_names = ["r_shoulder_pan_joint", "r_shoulder_lift_joint", "r_upper_arm_roll_joint", "r_elbow_flex_joint", "r_forearm_roll_joint", "r_wrist_flex_joint", "r_wrist_roll_joint"]
wrap_with_joint_velocity_limiter = false
joint_velocity_limits = []
complete_allowable_errors = [10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0]
complete_timeout_sec = 10.0
controller_name = "r_arm_controller"
state_topic_name = "r_arm_controller/openrr/state"
send_partial_joints_goal = false

[[ros_clients_configs]]
name = "torso"
joint_names = ["torso_lift_joint"]
wrap_with_joint_velocity_limiter = false
joint_velocity_limits = []
complete_allowable_errors = [10.0]
complete_timeout_sec = 10.0
controller_name = "torso_controller"
state_topic_name = "torso_controller/openrr/state"
send_partial_joints_goal = false

[openrr_clients_config]
urdf_path = "/opt/ros/melodic/share/robot_state_publisher/test/pr2.urdf"
self_collision_check_pairs = ["l_shoulder_pan_joint:r_shoulder_pan_joint"]
joints_poses = []

[[openrr_clients_config.joint_trajectory_clients_container_configs]]
name = "l_arm_with_torso"
clients_names = ["torso", "l_arm"]

[[openrr_clients_config.joint_trajectory_clients_container_configs]]
name = "r_arm_with_torso"
clients_names = ["torso", "r_arm"]

[[openrr_clients_config.collision_check_clients_configs]]
client_name = "l_arm_with_torso"
name = "l_arm_with_torso_collision_checked"

[openrr_clients_config.collision_check_clients_configs.self_collision_checker_config]
prediction = 0.001
time_interpolate_rate = 0.5

[[openrr_clients_config.collision_check_clients_configs]]
client_name = "r_arm_with_torso"
name = "r_arm_with_torso_collision_checked"

[openrr_clients_config.collision_check_clients_configs.self_collision_checker_config]
prediction = 0.001
time_interpolate_rate = 0.5

[[openrr_clients_config.ik_clients_configs]]
name = "l_arm_with_torso_ik"
client_name = "l_arm_with_torso_collision_checked"

[openrr_clients_config.ik_clients_configs.ik_solver_config]
ik_target = "l_gripper_palm_joint"
use_random_ik = false
allowable_position_error_m = 0.005
allowable_angle_error_rad = 0.005
jacobian_multiplier = 0.1
num_max_try = 100
constraints.position_x = true
constraints.position_y = true
constraints.position_z = true
constraints.rotation_x = true
constraints.rotation_y = true
constraints.rotation_z = true

[[openrr_clients_config.ik_clients_configs]]
name = "r_arm_with_torso_ik"
client_name = "r_arm_with_torso_collision_checked"

[openrr_clients_config.ik_clients_configs.ik_solver_config]
ik_target = "r_gripper_palm_joint"
use_random_ik = false
allowable_position_error_m = 0.005
allowable_angle_error_rad = 0.005
jacobian_multiplier = 0.1
num_max_try = 100
constraints.position_x = true
constraints.position_y = true
constraints.position_z = true
constraints.rotation_x = true
constraints.rotation_y = true
constraints.rotation_z = true
