ros_clients_configs = []
use_move_base_urdf_viz_web_client = true
use_navigation_urdf_viz_web_client = false
urdf_viz_clients_total_complete_allowable_error = 10.0
urdf_viz_clients_complete_timeout_sec = 10.0

[[urdf_viz_clients_configs]]
name = "arm"
joint_names = ["l_shoulder_yaw", "l_shoulder_pitch", "l_shoulder_roll", "l_elbow_pitch", "l_wrist_yaw", "l_wrist_pitch"]
wrap_with_joint_velocity_limiter = false
joint_velocity_limits = []

[openrr_clients_config]
urdf_path = "../../openrr-planner/sample.urdf"
self_collision_check_pairs = ["l_shoulder_yaw:l_gripper_linear1"]
joints_poses = []

[[openrr_clients_config.collision_check_clients_configs]]
name = "arm_collision_checked"
client_name = "arm"

[openrr_clients_config.collision_check_clients_configs.self_collision_checker_config]
prediction = 0.001
time_interpolate_rate = 0.5

[[openrr_clients_config.ik_clients_configs]]
name = "arm_ik"
client_name = "arm_collision_checked"

[openrr_clients_config.ik_clients_configs.ik_solver_config]
ik_target = "l_tool_fixed"
use_random_ik = false
allowable_position_error_m = 0.005
allowable_angle_error_rad = 0.005
jacobian_multiplier = 0.1
num_max_try = 100
constraints.position_x = true
constraints.position_y = true
constraints.position_z = true
constraints.rotation_x = true
constraints.rotation_y = true
constraints.rotation_z = true

