[[urdf_viz_clients_configs]]
name = "l_arm"
joint_names = [
    "l_shoulder_yaw",
    "l_shoulder_pitch",
    "l_shoulder_roll",
    "l_elbow_pitch",
    "l_wrist_yaw",
    "l_wrist_pitch",
]
wrap_with_joint_position_limiter = true
# If joint_position_limits is not specified, limits will be got from URDF.
# The following values are the same as if getting limits from URDF.
joint_position_limits = [
    { lower = -3.0, upper = 3.0 },
    { lower = -2.0, upper = 1.5 },
    { lower = -1.5, upper = 2.0 },
    { lower = -2.0, upper = 1.5 },
    { lower = -3.0, upper = 3.0 },
    { lower = -2.0, upper = 2.0 },
]

[[urdf_viz_clients_configs]]
name = "r_arm"
joint_names = [
    "r_shoulder_yaw",
    "r_shoulder_pitch",
    "r_shoulder_roll",
    "r_elbow_pitch",
    "r_wrist_yaw",
    "r_wrist_pitch",
]
wrap_with_joint_position_limiter = true
# If joint_position_limits is not specified, limits will be got from URDF.
# The following values are the same as if getting limits from URDF.
joint_position_limits = [
    { lower = -3.0, upper = 3.0 },
    { lower = -2.0, upper = 1.5 },
    { lower = -1.5, upper = 2.0 },
    { lower = -2.0, upper = 1.5 },
    { lower = -3.0, upper = 3.0 },
    { lower = -2.0, upper = 2.0 },
]

[openrr_clients_config]
urdf_path = "../../openrr-planner/sample.urdf"
self_collision_check_pairs = [
    "l_shoulder_yaw:l_gripper_linear1",
    "r_shoulder_yaw:r_gripper_linear1",
]

# Client config for left arm
[[openrr_clients_config.collision_check_clients_configs]]
name = "l_arm_collision_checked"
client_name = "l_arm"

[[openrr_clients_config.ik_clients_configs]]
name = "l_arm_ik"
client_name = "l_arm_collision_checked"
solver_name = "l_arm_ik_solver"

[[openrr_clients_config.joints_poses]]
pose_name = "zero"
client_name = "l_arm_collision_checked"
positions = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

[openrr_clients_config.ik_solvers_configs.l_arm_ik_solver]
ik_target = "l_tool_fixed"

# Client config for right arm
[[openrr_clients_config.collision_check_clients_configs]]
name = "r_arm_collision_checked"
client_name = "r_arm"

[[openrr_clients_config.ik_clients_configs]]
name = "r_arm_ik"
client_name = "r_arm_collision_checked"
solver_name = "r_arm_ik_solver"

[[openrr_clients_config.joints_poses]]
pose_name = "zero"
client_name = "r_arm_collision_checked"
positions = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

[openrr_clients_config.ik_solvers_configs.r_arm_ik_solver]
ik_target = "r_tool_fixed"
