robot_config_path = "ur10_robot_client_config_for_urdf_viz.toml"

[control_modes_config]
move_base_mode = "base"

[control_modes_config.joints_pose_sender_config]

[[control_modes_config.ik_mode_teleop_configs]]
solver_name = "arm_ik_solver"
joint_trajectory_client_name = "arm"

[control_modes_config.ik_mode_teleop_configs.config]
mode = "i k"

[[control_modes_config.joy_joint_teleop_configs]]
client_name = "arm_collision_checked"

[control_modes_config.joy_joint_teleop_configs.config]
mode = "arm"
