urdf_path = "../../../universal_robot/ur_description/urdf/ur10_robot.urdf"
self_collision_check_pairs = ["shoulder_pan_joint:elbow_joint"]
urdf_viz_clients_configs = []
use_move_base_urdf_viz_web_client = false
urdf_viz_clients_total_complete_allowable_error = 0.02
urdf_viz_clients_complete_timeout_sec = 10.0

[[ros_clients_configs]]
name = "arm"
joint_names = ["shoulder_pan_joint", "shoulder_lift_joint", "elbow_joint", "wrist_1_joint", "wrist_2_joint", "wrist_3_joint"]
wrap_with_joint_velocity_limiter = false
joint_velocity_limits = []
complete_allowable_errors = [0.01, 0.01, 0.01, 0.01, 0.01, 0.01]
complete_timeout_sec = 10.0
controller_name = "arm_controller"
send_partial_joints_goal = false

[[collision_check_clients_configs]]
name = "arm_collision_checked"
client_name = "arm"

[collision_check_clients_configs.self_collision_checker_config]
prediction = 0.001
time_interpolate_rate = 0.5

[[ik_clients_configs]]
name = "arm_ik"
client_name = "arm_collision_checked"

[ik_clients_configs.ik_solver_config]
ik_target = "ee_fixed_joint"
use_random_ik = false
allowable_position_error_m = 0.005
allowable_angle_error_rad = 0.01
jacobian_multiplier = 0.1
num_max_try = 3000
constraints.position_x = true
constraints.position_y = true
constraints.position_z = true
constraints.rotation_x = false
constraints.rotation_y = true
constraints.rotation_z = false

[[joints_poses]]
pose_name = "zero"
client_name = "arm_collision_checked"
positions = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

[[joints_poses]]
pose_name = "ready"
client_name = "arm_collision_checked"
positions = [0.0, -0.7, 1.4, -2.27, 0.0, 0.0]
