urdf_path = "../../../universal_robot/ur_description/urdf/ur10_robot.urdf"
self_collision_check_pairs = ["shoulder_pan_joint:elbow_joint"]
ros_clients_configs = []
joints_poses = []
use_move_base_urdf_viz_web_client = true
urdf_viz_clients_total_complete_allowable_error = 10.0
urdf_viz_clients_complete_timeout_sec = 10.0

[[urdf_viz_clients_configs]]
name = "arm"
joint_names = ["shoulder_pan_joint", "shoulder_lift_joint", "elbow_joint", "wrist_1_joint", "wrist_2_joint", "wrist_3_joint"]
wrap_with_joint_velocity_limiter = false
joint_velocity_limits = []

[[collision_check_clients_configs]]
name = "arm_collision_checked"
client_name = "arm"

[collision_check_clients_configs.self_collision_checker_config]
prediction = 0.001
time_interpolate_rate = 0.5

[[ik_clients_configs]]
name = "arm_ik"
client_name = "arm_collision_checked"

[ik_clients_configs.ik_solver_config]
ik_target = "ee_fixed_joint"
use_random_ik = false
allowable_position_error_m = 0.005
allowable_angle_error_rad = 0.005
jacobian_multiplier = 0.1
num_max_try = 100
constraints.position_x = true
constraints.position_y = true
constraints.position_z = true
constraints.rotation_x = true
constraints.rotation_y = false
constraints.rotation_z = true

