[package]
name = "openrr-gui"
version = "0.0.5"
authors = ["Taiki Endo <te316e89@gmail.com>"]
edition = "2018"
license = "Apache-2.0"
description = "openrr GUI library"
keywords = ["robotics", "robot"]
categories = ["science::robotics", "gui"]
repository = "https://github.com/openrr/openrr"
documentation = "https://docs.rs/openrr-gui"

[features]
default = ["assimp"]
assimp = ["openrr-client/assimp"]
# Enables the `iced_glow` renderer on GUI.
# This might be useful if the default renderer doesn't work.
glow = ["iced/glow"]

[dependencies]
arci = "0.0.5"
iced = "0.3"
openrr-client = { version = "0.0.5", default-features = false }
rand = "0.8"
thiserror = "1"
tracing = { version = "0.1", features = ["log"] }
urdf-rs = "0.6"
