[package]
name = "openrr-gui"
version = "0.0.6"
edition = "2021"
license = "Apache-2.0"
description = "openrr GUI library"
keywords = ["robotics", "robot"]
categories = ["science::robotics", "gui"]
repository = "https://github.com/openrr/openrr"

[features]
default = ["assimp"]
assimp = ["openrr-client/assimp"]
# Enables the `iced_glow` renderer on GUI.
# This might be useful if the default renderer doesn't work.
glow = ["iced/glow"]

[dependencies]
arci = "0.0.6"
iced = { version = "0.4.2", features = ["image"] }
iced_futures = { version = "0.4.1", features = ["tokio"] }
openrr-client = { version = "0.0.6", default-features = false }
rand = "0.8"
thiserror = "1"
tracing = { version = "0.1", features = ["log"] }
urdf-rs = "0.6"
