[package]
name = "openrr-gui"
version = "0.0.1"
authors = ["Taiki Endo <te316e89@gmail.com>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
arci = { version = "0.0.1", path = "../arci" }
iced = "0.2"
log = "0.4"
openrr-client = { version = "0.0.1", path = "../openrr-client" }
rand = "0.8"
thiserror = "1"
urdf-rs = "0.6"

[dev-dependencies]
anyhow = "1"
env_logger = "0.8"
openrr-apps = { version = "0.0.1", path = "../openrr-apps" }
structopt = "0.3.21"
