# Based on https://github.com/taiki-e/iced_style_config/blob/v0.1.0/examples/dark_theme.toml

[color]
SURFACE = [0.25, 0.27, 0.29] # ["0x40", "0x44", "0x4B"]
ACCENT = [0.44, 1.0, 0.91]   # ["0x6F", "0xFF", "0xE9"]
ACTIVE = [0.45, 0.54, 0.85]  # ["0x72", "0x89", "0xDA"]
HOVERED = [0.4, 0.48, 0.77]  # ["0x67", "0x7B", "0xC4"]
ERRORED = [1, 0, 0]

[button.default]
active.background = "ACTIVE"
active.border_radius = 3.0
active.text_color = "WHITE"
hovered.background = "HOVERED"
hovered.text_color = "WHITE"
pressed.border_width = 1.0
pressed.text_color = "WHITE"

[checkbox.default]
active.background = "SURFACE"
active.checkmark_color = "WHITE"
active.border_radius = 2.0
active.border_width = 1.0
active.border_color = "ACTIVE"
active.checked.background = "ACTIVE"
hovered.background = { rgb = "SURFACE", a = 0.8 }
hovered.checked.background = { rgb = "ACTIVE", a = 0.8 }
width = "fill"

[container.default]
background = ["0x36", "0x39", "0x3F"]
text_color = "WHITE"
width = "fill"
height = "fill"
align_x = "center"
align_y = "center"

[pick_list.default]
menu.background = "SURFACE"
menu.border_width = 0.0
menu.text_color = "WHITE"
menu.selected_background = "HOVERED"
active.background = "ACTIVE"
active.text_color = "WHITE"
active.border_width = 0.0
hovered.background = "HOVERED"

[progress_bar.default]
background = "SURFACE"
bar = "ACTIVE"
border_radius = 10.0

[rule.default]
color = "SURFACE"
width = 2
radius = 1.0
fill_mode = { padded = 15 }

[radio.default]
active.background = "SURFACE"
active.dot_color = "ACTIVE"
active.border_width = 1.0
active.border_color = "ACTIVE"
hovered.background = { rgb = "SURFACE", a = 0.5 }

[scrollable.default]
active.background = "SURFACE"
active.border_radius = 2.0
active.border_width = 0.0
active.border_color = "TRANSPARENT"
active.scroller.color = "ACTIVE"
active.scroller.border_radius = 2.0
active.scroller.border_width = 0.0
active.scroller.border_color = "TRANSPARENT"
hovered.background = { rgb = "SURFACE", a = 0.5 }
hovered.scroller.color = "HOVERED"
dragging.scroller.color = [0.85, 0.85, 0.85]

[slider.default]
active.rail_colors = ["ACTIVE", { rgb = "ACTIVE", a = 0.1 }]
active.handle.shape = { circle = { radius = 9.0 } }
active.handle.color = "ACTIVE"
active.handle.border_width = 0.0
active.handle.border_color = "TRANSPARENT"
hovered.handle.color = "HOVERED"
dragging.handle.color = [0.85, 0.85, 0.85]

[text_input.default]
active.background = "SURFACE"
active.border_radius = 2.0
active.border_width = 0.0
active.border_color = "TRANSPARENT"
focused.border_width = 1.0
focused.border_color = "ACCENT"
hovered.border_width = 1.0
hovered.border_color = { rgb = "ACTIVE", a = 0.3 }
placeholder_color = [0.4, 0.4, 0.4]
value_color = "WHITE"
selection_color = "ACTIVE"

[text_input.error]
active.background = "SURFACE"
active.border_radius = 2.0
active.border_width = 1.5
active.border_color = "ERRORED"
focused.border_color = "ERRORED"
placeholder_color = [0.4, 0.4, 0.4]
value_color = "WHITE"
selection_color = "ACTIVE"

[text.error]
color = "ERRORED"
size = 16
horizontal_alignment = "left"
width = "fill"
