[package]
name = "openrr-planner"
version = "0.0.1"
authors = ["Takashi Ogura <ogura@smilerobotics.com>"]
description = "Collision avoidance path planning for robotics"
license = "Apache-2.0"
keywords = ["pathplanning", "robotics"]
categories = ["algorithms"]
repository = "https://github.com/OpenRR/openrr"
readme = "README.md"
edition="2018"

[features]
default = [ "assimp" ]

[dependencies]
assimp = { version = "0.3", optional = true }
k = "0.21"
log = "0.4"
ncollide3d = "0.26"
num-traits = "0.2"
rand = "0.3.0"
rrt = "0.4.0"
thiserror = "1.0"
trajectory = "0.0.1"
urdf-rs = "0.4"

[dev-dependencies]
env_logger = "0.7"
kiss3d = "0.28"
structopt = "0.3"
urdf-viz = "0.22"
