[package]
name = "openrr-planner"
version = "0.0.5"
authors = ["Takashi Ogura <ogura@smilerobotics.com>"]
edition="2018"
license = "Apache-2.0"
description = "Collision avoidance path planning for robotics"
keywords = ["pathplanning", "robotics", "robot"]
categories = ["algorithms", "science::robotics"]
repository = "https://github.com/openrr/openrr"
documentation = "http://docs.rs/openrr-planner"

[features]
default = [ "assimp" ]

[dependencies]
assimp = { version = "0.3", optional = true }
k = "0.23"
ncollide3d = "0.28"
num-traits = "0.2"
rand = "0.8"
rrt = "0.5"
thiserror = "1.0"
tracing = { version = "0.1", features = ["log"] }
trajectory = "0.0.2"
urdf-rs = "0.6"

[dev-dependencies]
approx = "0.4.0"
kiss3d = "0.31"
structopt = "0.3"
tracing-subscriber = "0.2"
urdf-viz = "0.25"
