[package]
name = "openrr-planner"
version = "0.0.1"
authors = ["Takashi Ogura <ogura@smilerobotics.com>"]
edition="2018"
license = "Apache-2.0"
description = "Collision avoidance path planning for robotics"
keywords = ["pathplanning", "robotics", "robot"]
categories = ["algorithms", "science::robotics"]
repository = "https://github.com/openrr/openrr"
readme = "README.md"

[features]
default = [ "assimp" ]

[dependencies]
assimp = { version = "0.3", optional = true }
k = "0.22"
log = "0.4"
ncollide3d = "0.27"
num-traits = "0.2"
rand = "0.8"
rrt = "0.4.0"
thiserror = "1.0"
trajectory = "0.0.1"
urdf-rs = "0.6"

[dev-dependencies]
env_logger = "0.8"
kiss3d = "0.29"
structopt = "0.3"
urdf-viz = "0.23"
