name: Code Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - run: rustup component add llvm-tools-preview
      - run: sudo apt-get update
      # only for arci-gamepad-gilrs, arci-speak-audio
      - run: sudo apt-get install -y libudev-dev libasound2-dev
      # only for arci-ros test (roscore)
      - run: sudo apt-get install -y python-roslaunch python-rostopic
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-features
        env:
          RUSTFLAGS: '-Zinstrument-coverage'
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --no-fail-fast
        env:
          RUSTFLAGS: '-Zinstrument-coverage'
      # v0.7.1 causes below problems, so use old v0.6.1
      # https://github.com/mozilla/grcov/issues/555
      # https://github.com/mozilla/grcov/issues/575
      - run: curl -L https://github.com/mozilla/grcov/releases/download/v0.6.1/grcov-linux-x86_64.tar.bz2 | tar jxf -
      - run: ./grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore="**/tests/*.rs" --ignore="**/examples/*.rs" -o lcov.info
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v1
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          fail_ci_if_error: true
          file: lcov.info