name: Code Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  coverage:
    runs-on: ubuntu-latest
    container:
      image: docker://ros:melodic-ros-base
      options: --security-opt seccomp=unconfined
    steps:
      - uses: actions/checkout@v2
      - run: |
          apt-get update
          apt-get -y install curl libfreetype6-dev
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-03-04
          override: true
      - run: ci/ubuntu-install-dependencies.sh
      - run: cargo install cargo-tarpaulin
      - name: Generate code coverage
        run: |
          cargo +nightly-2021-03-04 tarpaulin --verbose --all-features --workspace --out Xml
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v1
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          fail_ci_if_error: true
