name: Code Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ci/ubuntu-install-dependencies.sh
      - run: |
          # ros2
          sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key  -o /usr/share/keyrings/ros-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
          # ros1
          sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
          sudo apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654

          sudo apt-get update
          sudo apt-get install -y \
            ros-noetic-ros-base ros-noetic-joy \
            ros-foxy-ros-core ros-foxy-geometry-msgs ros-foxy-nav2-msgs
      # rustfmt is for openrr-remote (tonic-build)
      # TODO: revert nightly-2021-07-01
      - run: rustup toolchain install nightly-2021-07-01 --component rustfmt,llvm-tools-preview && rustup default nightly-2021-07-01
      - run: cargo install cargo-llvm-cov
      - name: Generate code coverage
        run: |
          # for test of arci-ros2
          source /opt/ros/foxy/setup.bash
          # for test of arci-ros (roscore, rostopic)
          source /opt/ros/noetic/setup.bash
          cargo llvm-cov --verbose --all-features --workspace --lcov --output-path lcov.info
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
          fail_ci_if_error: true
