name: Code Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    shell: bash -ieo pipefail {0}

jobs:
  coverage:
    runs-on: ubuntu-latest
    container:
      image: docker://openrr/openrr-coverage-ci:ros2
      options: --security-opt seccomp=unconfined
    env:
      HOME: /root
    steps:
      - uses: actions/checkout@v2
      - run: ci/ubuntu-install-dependencies.sh
      - name: Generate code coverage
        run: |
          # for test of arci-ros2
          source /opt/ros/foxy/setup.bash
          # for test of arci-ros (roscore, rostopic)
          source /opt/ros/noetic/setup.bash
          cargo +nightly-2021-03-04 tarpaulin --verbose --all-features --workspace --out Xml --timeout 60
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v1
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          fail_ci_if_error: true
