name: ros1

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 15 * * *'

jobs:
  ros1_arci_ros:
    runs-on: ubuntu-18.04
    container:
      image: docker://ros:melodic-ros-base
    env:
      HOME: /root
    steps:
      - uses: actions/checkout@v2
      - run: |
          apt-get update
          apt-get -y install curl
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: cargo everything
        shell: bash -ieo pipefail {0}
        working-directory: arci-ros
        run: |
          source /opt/ros/melodic/setup.bash
          rosdep install -y -i --from-paths .
          cargo test

  ros1_openrr_apps:
    runs-on: ubuntu-18.04
    container:
      image: docker://ros:melodic-ros-base
    env:
      HOME: /root
    steps:
      - uses: actions/checkout@v2
      - run: |
          apt-get update
          apt-get -y install curl
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: ci/ubuntu-install-dependencies.sh
      - name: cargo test
        shell: bash -ieo pipefail {0}
        working-directory: openrr-apps
        run: |
          cargo test --no-default-features --features ros,assimp
