name: ros2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  ros2_arci_ros2:
    runs-on: ubuntu-20.04
    container:
      image: docker://ros:foxy
    env:
      HOME: /root
    steps:
      - uses: actions/checkout@v2
      - run: |
          apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
          apt-get update
          apt-get -y install curl libclang-dev
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: cargo build
        shell: bash -ieo pipefail {0}
        working-directory: arci-ros2
        run: |
          source /opt/ros/foxy/setup.bash
          cargo build --features ros2 --examples
      - name: cargo test
        shell: bash -ieo pipefail {0}
        working-directory: arci-ros2
        run: |
          source /opt/ros/foxy/setup.bash
          cargo test --features ros2
